### PR TITLE
Experiments with sse, very slow (what am I doing wrong?)

### PR DESCRIPTION
**Pull request by HEnquist**
This PR isn't meant to be merged!
I made a little attempt at using sse to speed up the length 4 butterfly. I made it as a quite ugly hack in the scalar butterfly, mostly for playing around. It works and gives correct results, but it's slow like a turtle!
The best way to handle sse would probably be to start off from the avx code instead, but that thing is huge and I wanted to just play a little first. Is there anything obviously wrong with my code?

### CODE REVIEW

**Comment by ejmahler** [comment]
When I ran into slower-than-expected performance when doing AVX things, the first thing I'd always do is check the assembly.

First, set this to #[inline(never)]
```
#[inline]
    #[target_feature(enable = "sse", enable = "sse2")]
    pub(crate) unsafe fn perform_fft_contiguous(
```

Then, compile something that's guaranteed to compile butterfly4 - the benchmarks ir the concurrency example is a good start, and output theassembly as you do so
`cargo rustc --release --bench bench_rustfft -- --emit=asm`

Then, go to `RustFFT\target\release\deps`, there should be a `bench_rustfft-34534523.s` file, where the numbers are random. this contains the generated assembly for the entire benchmark executable. open it in a text editor, and search for Butterfly4.

The function to compute the butterfly 4 will have a signature something like this:
`	.def	 _ZN94_$LT$rustfft..algorithm..butterflies..Butterfly4$LT$T$GT$$u20$as$u20$rustfft..Fft$LT$T$GT$$GT$20process_with_scratch17h5f6d3457ed567c55E` where again the hex symbols on the end are random.

You'll find multiple copies of it, monomorphized for f32 and f64. Here's what the f32 one looks like for me, without this PR:

```
	.def	 _ZN94_$LT$rustfft..algorithm..butterflies..Butterfly4$LT$T$GT$$u20$as$u20$rustfft..Fft$LT$T$GT$$GT$20process_with_scratch17h7e8b65d90fe6991eE;
	.scl	3;
	.type	32;
	.endef
	.section	.text,"xr",one_only,_ZN94_$LT$rustfft..algorithm..butterflies..Butterfly4$LT$T$GT$$u20$as$u20$rustfft..Fft$LT$T$GT$$GT$20process_with_scratch17h7e8b65d90fe6991eE
	.p2align	4, 0x90
_ZN94_$LT$rustfft..algorithm..butterflies..Butterfly4$LT$T$GT$$u20$as$u20$rustfft..Fft$LT$T$GT$$GT$20process_with_scratch17h7e8b65d90fe6991eE:
	cmpq	$4, %r8
	jb	.LBB1045_8
	movaps	__xmm@80000000800000008000000080000000(%rip), %xmm0
	movq	%r8, %rax
	jmp	.LBB1045_2
	.p2align	4, 0x90
.LBB1045_4:
	xorps	%xmm0, %xmm4
.LBB1045_5:
	movaps	%xmm3, %xmm5
	shufps	$132, %xmm4, %xmm5
	shufps	$32, %xmm5, %xmm2
	shufps	$36, %xmm2, %xmm3
	movaps	%xmm1, %xmm2
	addps	%xmm3, %xmm2
	subps	%xmm3, %xmm1
	movups	%xmm2, (%rdx)
	movups	%xmm1, 16(%rdx)
	addq	$32, %rdx
	cmpq	$3, %rax
	jbe	.LBB1045_6
.LBB1045_2:
	addq	$-4, %rax
	movsd	(%rdx), %xmm3
	movsd	8(%rdx), %xmm2
	movsd	16(%rdx), %xmm4
	movsd	24(%rdx), %xmm5
	movaps	%xmm3, %xmm1
	addps	%xmm4, %xmm1
	subps	%xmm4, %xmm3
	movlhps	%xmm3, %xmm1
	movaps	%xmm2, %xmm3
	addps	%xmm5, %xmm3
	subps	%xmm5, %xmm2
	movaps	%xmm2, %xmm4
	shufps	$229, %xmm2, %xmm4
	cmpb	$0, (%rcx)
	jne	.LBB1045_4
	xorps	%xmm0, %xmm2
	jmp	.LBB1045_5
.LBB1045_6:
	testq	%rax, %rax
	jne	.LBB1045_8
	retq
.LBB1045_8:
	movl	$4, %ecx
	movq	%r8, %rdx
	xorl	%r8d, %r8d
	xorl	%r9d, %r9d
	jmp	_ZN7rustfft6common17fft_error_inplace17hb2fed6d9a5972359E
```
It doesn't actually say f32 anywhere in here, the only reason I know it's f32 is because the in the instruction `addps`, the final characters 'ps' stand for *P*acked *S*ingle precision, aka, interpret 2 SSE vectors as 4 f32s each, and add them. If it says "pd", that stands for *P*acked *D*ouble precision.

It also might say `addss`, or `addsd`, which stand for *S*calar *S*ingle-precision and *S*calar *D*ouble-precision instead, which would only add the bottom-most float from each vector instead of all of them.

Notably, the first thing I'd look for is that you shouldn't see any function calls. You might see `jmp	_ZN7rustfft6common17fft_error_inplace17hb2fed6d9a5972359E` or something along those lines, which is normal and comes from the FFT butterfly macro, but if you see `call`, `callq`, or any other `jmp` instructions to things that look like they could be functions, that might be the source of the problem.

If there's nothing obvious, paste the assembly you're getting here for the f32 version and I might be able to give more insight.

**Comment by ejmahler** [comment]
One final note, if you mark `perform_fft_contiguous` as `#[inline_never]`, then you should look for that in the assembly instead of `process_with_scratch`

**Comment by HEnquist** [comment]
Thank you! This is exactly what I need to continue! I already found one problem, the _mm_permute_ps & pd are actually avx, not sse. I misread the rust core::arch documentation and thought that "sse, avx" means it's available in both, not that it needs both.. I also found that there is not need to put `#[target_feature(enable = "sse", enable = "sse2")]` since those are enabled by default anyway. Now I'll get rid of that permute and try again!

**Comment by HEnquist** [comment]
Some progress! Now plain length 4 butterflies are faster, but when used inside something else they are still slower.. more investigations needed!
```
 name                                 scalar.txt ns/iter  sse4_11.txt ns/iter  diff ns/iter   diff %  speedup 
 butterfly32_04                       36                  24                            -12  -33.33%   x 1.50 
 butterfly32_08                       150                 377                           227  151.33%   x 0.40 
 butterfly32_16                       683                 835                           152   22.25%   x 0.82 
 butterfly64_04                       49                  32                            -17  -34.69%   x 1.53 
 butterfly64_08                       178                 240                            62   34.83%   x 0.74 
 butterfly64_16                       774                 825                            51    6.59%   x 0.94 
```
On a side note, the "scalar" code isn't very scalar in practice. The compiler is really clever and manages to vectorize a lot of stuff.

**Comment by ejmahler** [comment]
Totally. I noticed when I pasted my version of the butterfly 4 asm code above, I noticed that it was partially vectorizing things. It seemed to be loading each complex number into its own vector. So it was reducing the number of operations, but it couldn't quote figure out that it could go farther.

**Comment by ejmahler** [comment]
I suspect that butterfly 8 and butterfly 16 are slower because they inline the call to butterfly 4 and very likely do a bunch of reordering of the instructions and such - and the conditionals + typeID stuff probably makes that inlining and reordering much less effective.

**Comment by HEnquist** [comment]
That seems like a very likely explanation. I got the answers I needed so I should probably close this PR now, but when I do the really useful little intrinsics guide will disappear from view and be forgotten. Seems like a waste, it could be useful for anyone trying to speed something up with intrinsics and I didn't find anything else like it when I was reading up on how to use instrinsics. But I don't know where to put it so others could also find it. Ideas?

**Comment by ejmahler** [comment]
The guide on how to inspect the assembly to debug intrinsics? Maybe I can write an internal rust users post for it.

For now, you can still access closed PRs.

**Comment by HEnquist** [comment]
> The guide on how to inspect the assembly to debug intrinsics? Maybe I can write an internal rust users post for it.
Yeah that's the one I meant. Something like that would be very useful maybe in some getting started section of the docs for the core::arch:: stuff.

**Pull request closed without merging**
