### PR TITLE
cargo fmt + refactoring

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by HEnquist** [comment]
I support this! Autoformatting the code makes it easier to read, when everything follows the same style. 
I would suggest adding something in the readme saying that all contributions should also be formatted with rustfmt.

**Comment by adamnemecek** [comment]
I can try adding a githook to run cargo fmt?

**Comment by adamnemecek** [comment]
@HEnquist added the note.

**Comment by ejmahler** [comment]
Agreed, the more people are working on this project the more useful it will be to have standardized formatting.

**Comment by ejmahler** [comment]
I made one change - benchmarks are inherently tabular, and imo benefit from being kept in a tabular format. So I added a rustfmt.toml and set it to ignore the benchmarks file.

Some day when macros support concatenating strings to create new identifiers, we can change the benchmarks to be macro-based, meaning they wouldn't need to be tabular to be readable anymore.

**Comment by ejmahler** [comment]
One thing I'd like your opinion on - I've seen projects set up a required check that runs cargo fmt, and fails if any files changed as a result of the formatting, AKA it forces you to run cargo fmt as a part of any PR, as opposed to just asking nicely. Should we do that here?

**Comment by HEnquist** [comment]
I like having the format check in the ci! I do that for my own projects and it really helps in keeping the code nice and clean. It also helps keeping the diffs free of formatting noise.

About running formatting with a git pre-commit hook, that is certainly possible. But there are also other ways to do it like having the editor format on save. Different people probably want to do it in different ways. The important thing is that it gets done and having the ci check makes sure of that.

**Comment by ejmahler** [comment]
In addition to merging, I also added rustfmt as another required check.

**Pull request merged**
